#
# Copyright 2005  Hon Hai Precision Ind. Co. Ltd.
#  All Rights Reserved.
# No porti

#For Compiler Option, add by Jasmine Yang, 03/27/2006
CONFIG_ACOS_MODULES=y
CONFIG_ACOSNAT=y
TELNET_ENABLE_FLAG=y
UPNP_ENABLE_FLAG=y
INTERNET_UPGRADE_FLAG=y
POT_ENABLE_FLAG=y
WAN_LAN_CONFLICT_ENABLE_FLAG=y
LLTD_ENABLE_FLAG=y
TRAFFIC_METER_FLAG=y
ACOS_TR069=y
UPNP_SMARTWIZARD_2_0=y
